baseURL = "https://dreamingchuchu.github.io/"
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'hugo-brewm-main'

[params.giscus]
  repo = "dreamingchuchu/my-hugo-blog"
  repoId = "R_kgDOQddrMw"
  categoryId = "DIC_kwDOQddrM84CzESd"
  mapping = "pathname" 
  reactionsEnabled = "1" 
  theme = "preferred_color_scheme"
  lang = "zh-CN"
  enable = true